[versions]
java = "25"
guice = "7.0.0"
slf4j = "2.0.17"
json = "2.0.60"
amqp = "5.26.0"
config = "1.4.3"
jakartaPersistence = "3.2.0"
jakartaInject = "2.0.1"
querydsl = "7.0"
mongodb = "5.6.1"
querydslmongodb = "7.0"
classgraph = "4.8.184"
querydslapt = "7.1"
hibernate = "7.1.5.Final"
querydslJpa = "7.1"
jakartaTransaction = "2.0.1"

[libraries]

# Logging Facade
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

# RabbitMQ driver (AMQP protocol to RabbitMQ Message Broker)
amqp = { module = "com.rabbitmq:amqp-client", version.ref = "amqp" }

# Dependency injection (DI) framework. JSR 330 Compliant
guice = { module = "com.google.inject:guice", version.ref = "guice" }

# High performance JSON library
json = { module = "com.alibaba.fastjson2:fastjson2", version.ref = "json" }

# Configuration library
config = { module = "com.typesafe:config", version.ref = "config" }

# MongoDB driver.
mongodb = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongodb" }
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
querydslmongodb = { module = "io.github.openfeign.querydsl:querydsl-mongodb", version.ref = "querydslmongodb" }

# QueryDSL. Type-safe, dynamic and composable query syntex for Java
querydsl = { module = "io.github.openfeign.querydsl:querydsl-core", version.ref = "querydsl" }
querydslJpa = { module = "io.github.openfeign.querydsl:querydsl-jpa", version.ref = "querydslJpa" }

# RDBMS ORM
hibernate = { module = "org.hibernate.orm:hibernate-core", version.ref = "hibernate" }

# JDBC connection pooling
hikaricp = { module = "org.hibernate.orm:hibernate-hikaricp", version.ref = "hibernate" }

# Jakarta standardized APIs
jakarta-inject = { module = "jakarta.inject:jakarta.inject-api", version.ref = "jakartaInject" }
jakarta-transaction = { module = "jakarta.transaction:jakarta.transaction-api", version.ref = "jakartaTransaction" }
jakarta-persistence = { module = "jakarta.persistence:jakarta.persistence-api", version.ref = "jakartaPersistence" }